# Destination folder to downloaded files.
destination: ./files

# Receita Federal website URL that contains all available database versions.
versions_url: https://arquivos.receitafederal.gov.br/dados/cnpj/dados_abertos_cnpj

# Skips the download if a same name file exists in destination folder.
skip_existent_files: false

# Skips the download of following filenames.
skip_files:
  - Empresas0.zip
  # - Empresas1.zip
  # - Empresas2.zip
  # - Empresas3.zip
  # - Empresas4.zip
  # - Empresas5.zip
  # - Empresas6.zip
  # - Empresas7.zip
  # - Empresas8.zip
  # - Empresas9.zip
  - Estabelecimentos0.zip
  # - Estabelecimentos1.zip
  # - Estabelecimentos2.zip
  # - Estabelecimentos3.zip
  # - Estabelecimentos4.zip
  # - Estabelecimentos5.zip
  # - Estabelecimentos6.zip
  # - Estabelecimentos7.zip
  # - Estabelecimentos8.zip
  # - Estabelecimentos9.zip
  # - Socios1.zip
  # - Socios2.zip
  # - Socios3.zip
  # - Socios4.zip
  # - Socios5.zip
  # - Socios6.zip
  # - Socios7.zip
  # - Socios8.zip
  # - Socios9.zip
